spring:
  # DATABASE INFO
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: woqja5164!
  # JPA 사용시
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

custom:
  jwt-secret: 'rhwoqjacjswo'
  upload-path:
    images: 'C:/Users/User/workspace/uploads'